### ISSUE TITLE
Comece a usar o gitignore e remova arquivos e pastas indesejados do projeto.

### ISSUE THREAD

**Issue by ghost** [Carlos-Guilherme/quiz#1]
Mano eu tava dando uma olhada no teu projeto e vi que você acabou commitando a pasta do __pycache__ (onde ficam os arquivos .pyc (bytecode das vezes em que você interpretou um arquivo .py)), isso não é necessariamente ruim mas é algo indesejado na grande maioria dos projetos. Pra aumentar o profissionalismo dentro dos teus repositórios uma estratégia elegante seria não commitar arquivos ou pastas indesejados (como arquivos .pyc, ou até mesmo arquivos executáveis em situações específicas).

Pra fazer o git não considerar esses arquivos e pastas indesejados na hora do commit, comece a usar o recurso - arquivo - gitignore do próprio git, você pode criar um quando está inicializando o seu repositório, basta você clicar em "adicionar gitignore" e selecionar um template pra linguagem em que será usada no projeto (no seu caso, o template seria um para python), agora criar um gitignore com os arquivos já commitados é pífio, mas você pode começar a usar esse recurso para melhorar os seus futuros projetos, no mais, remova as pastas/arquivos indesejados que já estão commitados do branche main. (__pycache__ dentre outras coisas)

**Comment by Carlos-Guilherme** [comment]
opa mano, valeu pela ajuda! erei implementar isso da próxima vez! mais uma vez, obrigado.Em 8 de nov de 2020 21:27, _Maurinho <notifications@github.com> escreveu:

Mano eu tava dando uma olhada no teu projeto e vi que você acabou commitando a pasta do pycache (onde ficam os arquivos .pyc (bytecode das vezes em que você interpretou um arquivo .py)), isso não é necessariamente ruim mas é algo indesejado na grande maioria dos projetos. Pra aumentar o profissionalismo dentro dos teus repositórios uma estratégia elegante seria não commitar arquivos ou pastas indesejados (como arquivos .pyc, ou até mesmo arquivos executáveis em situações específicas).

Pra fazer o git não considerar esses arquivos e pastas indesejados, comece a usar o recurso - arquivo - gitignore do próprio git, você pode criar um quando está inicializando o seu repositório, basta você clicar em "adicionar gitignore" e selecionar um template pra linguagem em que será usada no projeto (no seu caso, o template seria um para python), agora criar um gitignore com os arquivos já commitados é pífio, mas você pode começar a usar esse recurso para melhorar os seus futuros projetos, no mais, remova as pastas/arquivos indesejados que já estão commitados do branche main. (pycache dentre outras coisas)
